name: Deployment Workflow
on: 
  push:
    branches: [master]

jobs:
  Pull-Code:
    runs-on: ubuntu-latest
    steps:
      - name: SSH 
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USER}}
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: |
            cd /var/www/timesheets-generator
            git pull origin master
            git status
            composer install --optimize-autoloader --no-dev
            npm run prod 